# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
naive_bayes <- function(r_train_feats, r_test_feats, r_train_labels, r_test_labels, num_classes) {
    invisible(.Call('_viewmaster_naive_bayes', PACKAGE = 'viewmaster', r_train_feats, r_test_feats, r_train_labels, r_test_labels, num_classes))
}

#' @export
prandu_main <- function(perc) {
    invisible(.Call('_viewmaster_prandu_main', PACKAGE = 'viewmaster', perc))
}

rcpparrayfire_hello_world <- function() {
    .Call('_viewmaster_rcpparrayfire_hello_world', PACKAGE = 'viewmaster')
}

#' @export
test_backends <- function() {
    .Call('_viewmaster_test_backends', PACKAGE = 'viewmaster')
}

computeSparseRowVariances <- function(j, val, rm, n) {
    .Call('_viewmaster_computeSparseRowVariances', PACKAGE = 'viewmaster', j, val, rm, n)
}

